apiVersion: v1
kind: Secret
metadata:
  name: credentials
  labels:
    app: app
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
type: Opaque
data:
  password: {{ .Values.password | b64enc | quote }}