apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-python
  namespace: dev
spec:
  project: default
  source:
    repoURL: https://github.com/HayderSarhan/S25-core-course-labs.git
    targetRevision: lab13
    path: k8s/app-python
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}