name: Moscow Time Web Application CI

on:
  push:
    branches:
      - main
      - lab3

jobs:

  test:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: app_python

    - name: Run linter (Flake8)
      run: |
        pip install flake8
        flake8 .
      working-directory: app_python

    - name: Run tests with pytest
      run: pytest
      working-directory: app_python

  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    - name: Build Docker image
      run: docker build -t hayderuni/moscow-time-flask:latest .
      working-directory: app_python

    - name: Push Docker image to Docker Hub
      run: docker push hayderuni/moscow-time-flask:latest
      working-directory: app_python
