name: Moscow Time Web Application CI

on:
  push:
    branches:
      - main
      - lab3

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        # setup-python action caches the python packages to speed up the workflow (https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages)
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r requirements.txt
      working-directory: app_python

    - name: Run linter (Flake8) & Tests (pytest)
      run: |
        flake8 .
        pytest
      working-directory: app_python

  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.8@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

  docker:
    runs-on: ubuntu-latest
    # Make sure the image is not built & pushed to docker hub if the test
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: app_python
        push: true
        tags: hayderuni/moscow-time-flask:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
